### PR TITLE
Transform the static index.html page into a rdf2h dinamic one

### PR DESCRIPTION
**Pull request by alemela**
I've converted the html page crafted as homepage into a rdf2h mapper. The final rendering is the same.

### CODE REVIEW

**Comment by ktk** [comment]
Thanks this seems to work fine, I triplifyed all other sites now.

However, it looks a bit strange:

* Font is super small
* This blue color is strange
* Especially behind the data.admin.ch text on top left

screen shot 2016-05-20 at 12 26 10

**Comment by ktk** [comment]
I merged this one as it's a great base. Can we address the design in another pull?

**Comment by retog** [comment]
I like the design aesthetically but I agree font size and contrasts might need some rework.

**Comment by ktk** [comment]
Beside the strange background color on top left it looks ok on the main page but it's pretty strange on the rest of the pages where we have almost no content so far. Maybe we need a default content-class for everything else which does not use those boxes.

And it's not clearly visible in the screenshot but the font is not small, it's tiny. Hardly readable.

**Comment by alemela** [comment]
Yes, on my first local test there wasn't that strange background. I must fix it. I will also look after the font; my idea was to use simply the boostrap one, but probably occurred some css misconfiguration.

For content pages I agree that boxes couldn't be always the best solution. In order to craft a default content class (without boxes), could you give me some directions about contents? Or I can imagine to use a lorem ipsum?

**Pull request merged**
